DROP TABLE PROFILE;
DROP TABLE CREDENTIALS;

CREATE TABLE CREDENTIALS
(
    USER_ID       BIGINT AUTO_INCREMENT,
    EMAIL         VARCHAR(30),
    PASSWORD_HASH VARCHAR(64),
    CONSTRAINT CREDENTIALS_PK PRIMARY KEY (USER_ID),
    CONSTRAINT CREDENTIALS_UNIQ UNIQUE (EMAIL)
);

CREATE TABLE PROFILE
(
    USER_ID    BIGINT,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME  VARCHAR(20),
    GENDER     TINYINT, # 1 for male, 0 for female
    COUNTRY    VARCHAR(20),
    CONSTRAINT PROFILE_PK PRIMARY KEY (USER_ID),
    CONSTRAINT PROFILE_FK FOREIGN KEY (USER_ID) REFERENCES CREDENTIALS (USER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE CLASSES
(
    POST_ID BIGINT AUTO_INCREMENT,
    TOPIC   VARCHAR(100),
    TEACHER VARCHAR(100),
    DATE    DATE,
    TIME    TIME,
    ONLINE  TINYINT, #ONLY 0 OR 1
    ADDRESS VARCHAR(100),
    CONSTRAINT CLASSES_PK PRIMARY KEY (POST_ID)
);

/* user's daily tasks*/
CREATE TABLE DAILY_PLANS
(
    TASK_ID BIGINT AUTO_INCREMENT,
    USER_ID BIGINT,
    DATE DATETIME,
    START_TIME TIME,
    END_TIME TIME,
    TASK_NAME VARCHAR(50),
    DESCRIPTION MEDIUMBLOB,
    CONSTRAINT DAILY_TASKS_PK PRIMARY KEY (TASK_ID),
    CONSTRAINT DAILY_TASKS_FK FOREIGN KEY (USER_ID) REFERENCES CREDENTIALS(USER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


insert into daily_plans (user_id, task_name, date, start_time, end_time) values(1, 'homework', date(now()), time(now()), time(now()));
insert into daily_plans (user_id, task_name, date, start_time, end_time) values(1, 'read quran', date(now()), time(now()), time(now()));
insert into daily_plans (user_id, task_name, date, start_time, end_time) values(1, 'read hadith', date(now()), time(now()), time(now()));

CREATE TABLE POSTS (
  POST_ID BIGINT AUTO_INCREMENT,
  USER_ID BIGINT,
  USER_NAME VARCHAR(50),
  TOPIC VARCHAR(255),
  DATE DATE,
  TIME TIME,
  CONSTRAINT POSTS_PK PRIMARY KEY (POST_ID),
  CONSTRAINT POSTS_FK FOREIGN KEY(USER_ID) REFERENCES CREDENTIALS(USER_ID)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE Comments (
  Comment_ID BIGINT AUTO_INCREMENT,
  Post_ID BIGINT,
  User_ID BIGINT,
  USER_NAME VARCHAR(50),
  Comment_Text VARCHAR(255),
  DATE DATE,
  TIME TIME,
  CONSTRAINT Comments_PK PRIMARY KEY (Comment_ID),
  CONSTRAINT Comments_FK_Post FOREIGN KEY (Post_ID) REFERENCES Posts (Post_ID)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE CATEGORY(
  CAT_ID BIGINT AUTO_INCREMENT,
  CAT_DESC VARCHAR(50),
  CONSTRAINT CAT_PK PRIMARY KEY (CAT_ID)
);

CREATE TABLE DUA (
  DUA_ID BIGINT AUTO_INCREMENT,
  CAT_ID BIGINT,
  TITLE VARCHAR(100),
  DUA_TEXT TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  MEANING TEXT,
  SOURCE VARCHAR(50),
  CONSTRAINT DUA_PK PRIMARY KEY (DUA_ID),
  CONSTRAINT DUA_FK FOREIGN KEY (CAT_ID) REFERENCES CATEGORY (CAT_ID)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);
